spring:
  application:
    name: assets
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 12MB
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://127.0.0.1:5432/mydatabase}
    username: ${DATABASE_USERNAME:myuser}
    password: ${DATABASE_PASSWORD:mysecretpassword}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-init-sql: SET TIME ZONE 'Europe/Kyiv'
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  properties:
    hibernate:
      format_sql: true
      jdbc:
        time_zone: Europe/Kyiv
        lob:
          non_contextual_creation: true
server:
  port: 8081

jwt:
  secret: ${JWT_SECRET}
  expiration: 3600000